AzureStorage/Models/Task.cs
using Microsoft.WindowsAzure.Storage.Table;
using System;

namespace AzureStorage.Models
{
    public class Task : TableEntity
    {
        public string Description
        {
            get
            {
                return PartitionKey;
            }
            set
            {
                PartitionKey = value;
            }
        }

        public string CreatedDate
        {
            get
            {
                return RowKey;
            }
            set
            {
                RowKey = value;
            }
        }
    }
}

AzureStorage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzureStorage.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AzureStorage/Controllers/StorageController.cs
using AzureStorage.Models;
using AzureStorage.Services;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace AzureStorage.Controllers
{
    /// <summary>
    /// Storage Controller
    /// </summary>
    public class StorageController : Controller
    {
        private AzureService _azureService;

        /// <summary>
        /// Constructor
        /// </summary>
        public StorageController()
        {
            _azureService = new AzureService();
        }

        // GET: Storage/Blobs
        public ActionResult Blobs()
        {
            // List of Blobs
            var blobsList = _azureService.GetAllBlobsFromContainer();

            return View(blobsList);
        }

        // POST: Storage/SaveFile
        [HttpPost]
        public ActionResult SaveFile(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                _azureService.SaveFileToBlob(fileName, file.InputStream);
            }

            return RedirectToAction("Blobs");
        }

        // GET: Storage/Queues
        public ActionResult Queues()
        {
            // List of messages
            var messagesList = _azureService.GetAllMessagesFromQueue();

            return View(messagesList);
        }

        // POST: Storage/Queues
        [HttpPost]
        public ActionResult Queues(string message)
        {
            _azureService.SaveMessageToQueue(message);

            return RedirectToAction("Queues");
        }

        // GET: Storage/Tables
        public ActionResult Tables()
        {
            // List of Tasks
            var tasksList = _azureService.GetAllTasksFromTable();

            return View(tasksList);
        }

        // POST: Storage/Tables
        [HttpPost]
        public ActionResult Tables(Task task)
        {
            _azureService.SaveTaskToTable(task);

            return RedirectToAction("Tables");
        }
    }
}

AzureStorage/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Storage Index";
}

<h1>Microsoft Azure</h1>
<ul>
    <li>34 datacenter regions</li>
    <li>85% of Fortune 500 companies use the Microsoft Cloud</li>
    <li>120,00 new Azure customer subscriptions per month</li>
</ul>

AzureStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Azure Tech Talk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Azure Tech Talk", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blobs", "Blobs", "Storage")</li>
                    <li>@Html.ActionLink("Queues", "Queues", "Storage")</li>
                    <li>@Html.ActionLink("Tables", "Tables", "Storage")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Azure Tech Talk</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AzureStorage/Views/Storage/Blobs.cshtml
@model List<string>

@{
    ViewBag.Title = "Blobs";
}

<form method="post" action="SaveFile" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="file" />
    </div>
    
    <button type="submit" class="btn btn-success">Submit</button>
</form>

<h1>List of Blobs</h1>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Blob Name</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var blob in Model)
            {
                <tr>
                    <td>@blob</td>
                </tr>
            }
        }
    </tbody>
</table>

AzureStorage/Views/Storage/Queues.cshtml
@model List<string>

@{
    ViewBag.Title = "Queues";
}

<form method="post">
    <div class="form-group">
        <label for="message">Message:</label>
        <input name="message" type="text" class="form-control" />
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
</form>

<h1>List of Messages</h1>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Message</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var message in Model)
            {
                <tr>
                    <td>@message</td>
                </tr>
            }
        }
    </tbody>
</table>

AzureStorage/Views/Storage/Tables.cshtml
@model List<AzureStorage.Models.Task>

@{
    ViewBag.Title = "Tables";
}

<form method="post">
    <div class="form-group">
        <label for="description">Description:</label>
        <input name="description" type="text" class="form-control" />
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
</form>

<h1>List of Tasks</h1>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Description</th>
            <td>Created On</td>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var task in Model)
            {
                <tr>
                    <td>@task.Description</td>
                    <td>@task.CreatedDate</td>
                </tr>
            }
        }
    </tbody>
</table>